services:
  - type: web
    name: veezo-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_TOKEN
        sync: false
